// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace QuizApp.Data.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    partial class QuizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizApp.Data.Entities.Answer", b =>
                {
                    b.Property<int>("IdAnswer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnswer"));

                    b.Property<int>("IdQuestion")
                        .HasColumnType("int");

                    b.Property<bool>("IsTrue")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAnswer");

                    b.HasIndex("IdQuestion");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            IdAnswer = 1,
                            IdQuestion = 1,
                            IsTrue = true,
                            Text = "Common Language Runtime"
                        },
                        new
                        {
                            IdAnswer = 2,
                            IdQuestion = 1,
                            IsTrue = false,
                            Text = "Central Logic Register"
                        },
                        new
                        {
                            IdAnswer = 3,
                            IdQuestion = 1,
                            IsTrue = false,
                            Text = "Class Loader Runtime"
                        },
                        new
                        {
                            IdAnswer = 4,
                            IdQuestion = 1,
                            IsTrue = false,
                            Text = "Code Level Resource"
                        },
                        new
                        {
                            IdAnswer = 5,
                            IdQuestion = 2,
                            IsTrue = true,
                            Text = "Typem referencyjnym"
                        },
                        new
                        {
                            IdAnswer = 6,
                            IdQuestion = 2,
                            IsTrue = false,
                            Text = "Typem wartościowym"
                        },
                        new
                        {
                            IdAnswer = 7,
                            IdQuestion = 2,
                            IsTrue = false,
                            Text = "Typem logicznym"
                        },
                        new
                        {
                            IdAnswer = 8,
                            IdQuestion = 2,
                            IsTrue = false,
                            Text = "Typem dynamicznym"
                        },
                        new
                        {
                            IdAnswer = 9,
                            IdQuestion = 3,
                            IsTrue = true,
                            Text = "Iteruje po kolekcji"
                        },
                        new
                        {
                            IdAnswer = 10,
                            IdQuestion = 3,
                            IsTrue = false,
                            Text = "Tworzy klasę"
                        },
                        new
                        {
                            IdAnswer = 11,
                            IdQuestion = 3,
                            IsTrue = false,
                            Text = "Kończy program"
                        },
                        new
                        {
                            IdAnswer = 12,
                            IdQuestion = 3,
                            IsTrue = false,
                            Text = "Obsługuje wyjątki"
                        },
                        new
                        {
                            IdAnswer = 13,
                            IdQuestion = 4,
                            IsTrue = true,
                            Text = "Przestrzeń nazw"
                        },
                        new
                        {
                            IdAnswer = 14,
                            IdQuestion = 4,
                            IsTrue = false,
                            Text = "Typ zmiennej"
                        },
                        new
                        {
                            IdAnswer = 15,
                            IdQuestion = 4,
                            IsTrue = false,
                            Text = "Biblioteka DLL"
                        },
                        new
                        {
                            IdAnswer = 16,
                            IdQuestion = 4,
                            IsTrue = false,
                            Text = "Metoda"
                        },
                        new
                        {
                            IdAnswer = 17,
                            IdQuestion = 5,
                            IsTrue = true,
                            Text = "new"
                        },
                        new
                        {
                            IdAnswer = 18,
                            IdQuestion = 5,
                            IsTrue = false,
                            Text = "create"
                        },
                        new
                        {
                            IdAnswer = 19,
                            IdQuestion = 5,
                            IsTrue = false,
                            Text = "make"
                        },
                        new
                        {
                            IdAnswer = 20,
                            IdQuestion = 5,
                            IsTrue = false,
                            Text = "build"
                        },
                        new
                        {
                            IdAnswer = 21,
                            IdQuestion = 6,
                            IsTrue = true,
                            Text = "Structured Query Language"
                        },
                        new
                        {
                            IdAnswer = 22,
                            IdQuestion = 6,
                            IsTrue = false,
                            Text = "Simple Query List"
                        },
                        new
                        {
                            IdAnswer = 23,
                            IdQuestion = 6,
                            IsTrue = false,
                            Text = "System Query Logic"
                        },
                        new
                        {
                            IdAnswer = 24,
                            IdQuestion = 6,
                            IsTrue = false,
                            Text = "Standard Question Lang."
                        },
                        new
                        {
                            IdAnswer = 25,
                            IdQuestion = 7,
                            IsTrue = true,
                            Text = "Pobierania danych"
                        },
                        new
                        {
                            IdAnswer = 26,
                            IdQuestion = 7,
                            IsTrue = false,
                            Text = "Usuwania danych"
                        },
                        new
                        {
                            IdAnswer = 27,
                            IdQuestion = 7,
                            IsTrue = false,
                            Text = "Tworzenia tabel"
                        },
                        new
                        {
                            IdAnswer = 28,
                            IdQuestion = 7,
                            IsTrue = false,
                            Text = "Zmiany struktury"
                        },
                        new
                        {
                            IdAnswer = 29,
                            IdQuestion = 8,
                            IsTrue = true,
                            Text = "Zbiór danych w wierszach i kolumnach"
                        },
                        new
                        {
                            IdAnswer = 30,
                            IdQuestion = 8,
                            IsTrue = false,
                            Text = "Plik tekstowy"
                        },
                        new
                        {
                            IdAnswer = 31,
                            IdQuestion = 8,
                            IsTrue = false,
                            Text = "Program"
                        },
                        new
                        {
                            IdAnswer = 32,
                            IdQuestion = 8,
                            IsTrue = false,
                            Text = "Serwer"
                        },
                        new
                        {
                            IdAnswer = 33,
                            IdQuestion = 9,
                            IsTrue = true,
                            Text = "Unikalny identyfikator"
                        },
                        new
                        {
                            IdAnswer = 34,
                            IdQuestion = 9,
                            IsTrue = false,
                            Text = "Hasło użytkownika"
                        },
                        new
                        {
                            IdAnswer = 35,
                            IdQuestion = 9,
                            IsTrue = false,
                            Text = "Relację tabel"
                        },
                        new
                        {
                            IdAnswer = 36,
                            IdQuestion = 9,
                            IsTrue = false,
                            Text = "Indeks bazy"
                        },
                        new
                        {
                            IdAnswer = 37,
                            IdQuestion = 10,
                            IsTrue = true,
                            Text = "Brak wartości"
                        },
                        new
                        {
                            IdAnswer = 38,
                            IdQuestion = 10,
                            IsTrue = false,
                            Text = "Zero"
                        },
                        new
                        {
                            IdAnswer = 39,
                            IdQuestion = 10,
                            IsTrue = false,
                            Text = "Pusty tekst"
                        },
                        new
                        {
                            IdAnswer = 40,
                            IdQuestion = 10,
                            IsTrue = false,
                            Text = "Błąd danych"
                        },
                        new
                        {
                            IdAnswer = 41,
                            IdQuestion = 11,
                            IsTrue = true,
                            Text = "Central Processing Unit"
                        },
                        new
                        {
                            IdAnswer = 42,
                            IdQuestion = 11,
                            IsTrue = false,
                            Text = "Computer Personal Unit"
                        },
                        new
                        {
                            IdAnswer = 43,
                            IdQuestion = 11,
                            IsTrue = false,
                            Text = "Central Program Utility"
                        },
                        new
                        {
                            IdAnswer = 44,
                            IdQuestion = 11,
                            IsTrue = false,
                            Text = "Control Process User"
                        },
                        new
                        {
                            IdAnswer = 45,
                            IdQuestion = 12,
                            IsTrue = true,
                            Text = "Pamięć operacyjna"
                        },
                        new
                        {
                            IdAnswer = 46,
                            IdQuestion = 12,
                            IsTrue = false,
                            Text = "Dysk twardy"
                        },
                        new
                        {
                            IdAnswer = 47,
                            IdQuestion = 12,
                            IsTrue = false,
                            Text = "Procesor"
                        },
                        new
                        {
                            IdAnswer = 48,
                            IdQuestion = 12,
                            IsTrue = false,
                            Text = "Karta graficzna"
                        },
                        new
                        {
                            IdAnswer = 49,
                            IdQuestion = 13,
                            IsTrue = true,
                            Text = "Zarządza sprzętem i programami"
                        },
                        new
                        {
                            IdAnswer = 50,
                            IdQuestion = 13,
                            IsTrue = false,
                            Text = "Edytor tekstu"
                        },
                        new
                        {
                            IdAnswer = 51,
                            IdQuestion = 13,
                            IsTrue = false,
                            Text = "Gra komputerowa"
                        },
                        new
                        {
                            IdAnswer = 52,
                            IdQuestion = 13,
                            IsTrue = false,
                            Text = "Przeglądarka"
                        },
                        new
                        {
                            IdAnswer = 53,
                            IdQuestion = 14,
                            IsTrue = true,
                            Text = "Łączy sieci komputerowe"
                        },
                        new
                        {
                            IdAnswer = 54,
                            IdQuestion = 14,
                            IsTrue = false,
                            Text = "Chłodzi komputer"
                        },
                        new
                        {
                            IdAnswer = 55,
                            IdQuestion = 14,
                            IsTrue = false,
                            Text = "Przechowuje dane"
                        },
                        new
                        {
                            IdAnswer = 56,
                            IdQuestion = 14,
                            IsTrue = false,
                            Text = "Wyświetla obraz"
                        },
                        new
                        {
                            IdAnswer = 57,
                            IdQuestion = 15,
                            IsTrue = true,
                            Text = "Adres urządzenia w sieci"
                        },
                        new
                        {
                            IdAnswer = 58,
                            IdQuestion = 15,
                            IsTrue = false,
                            Text = "Hasło WiFi"
                        },
                        new
                        {
                            IdAnswer = 59,
                            IdQuestion = 15,
                            IsTrue = false,
                            Text = "Typ kabla"
                        },
                        new
                        {
                            IdAnswer = 60,
                            IdQuestion = 15,
                            IsTrue = false,
                            Text = "System operacyjny"
                        });
                });

            modelBuilder.Entity("QuizApp.Data.Entities.Question", b =>
                {
                    b.Property<int>("IdQuestion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuestion"));

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdQuiz")
                        .HasColumnType("int");

                    b.HasKey("IdQuestion");

                    b.HasIndex("IdQuiz");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            IdQuestion = 1,
                            Contents = "Co oznacza skrót CLR?",
                            IdQuiz = 1
                        },
                        new
                        {
                            IdQuestion = 2,
                            Contents = "Jakim typem jest string?",
                            IdQuiz = 1
                        },
                        new
                        {
                            IdQuestion = 3,
                            Contents = "Do czego służy foreach?",
                            IdQuiz = 1
                        },
                        new
                        {
                            IdQuestion = 4,
                            Contents = "Co to jest namespace?",
                            IdQuiz = 1
                        },
                        new
                        {
                            IdQuestion = 5,
                            Contents = "Jakie słowo tworzy obiekt?",
                            IdQuiz = 1
                        },
                        new
                        {
                            IdQuestion = 6,
                            Contents = "Co oznacza skrót SQL?",
                            IdQuiz = 2
                        },
                        new
                        {
                            IdQuestion = 7,
                            Contents = "Do czego służy SELECT?",
                            IdQuiz = 2
                        },
                        new
                        {
                            IdQuestion = 8,
                            Contents = "Co to jest tabela?",
                            IdQuiz = 2
                        },
                        new
                        {
                            IdQuestion = 9,
                            Contents = "Co oznacza PRIMARY KEY?",
                            IdQuiz = 2
                        },
                        new
                        {
                            IdQuestion = 10,
                            Contents = "Co oznacza NULL?",
                            IdQuiz = 2
                        },
                        new
                        {
                            IdQuestion = 11,
                            Contents = "Co oznacza skrót CPU?",
                            IdQuiz = 3
                        },
                        new
                        {
                            IdQuestion = 12,
                            Contents = "Do czego służy pamięć RAM?",
                            IdQuiz = 3
                        },
                        new
                        {
                            IdQuestion = 13,
                            Contents = "Co to jest system operacyjny?",
                            IdQuiz = 3
                        },
                        new
                        {
                            IdQuestion = 14,
                            Contents = "Do czego służy router?",
                            IdQuiz = 3
                        },
                        new
                        {
                            IdQuestion = 15,
                            Contents = "Co to jest adres IP?",
                            IdQuiz = 3
                        });
                });

            modelBuilder.Entity("QuizApp.Data.Entities.Quiz", b =>
                {
                    b.Property<int>("IdQuiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuiz"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdQuiz");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            IdQuiz = 1,
                            CategoryName = "C# – podstawy"
                        },
                        new
                        {
                            IdQuiz = 2,
                            CategoryName = "Bazy danych"
                        },
                        new
                        {
                            IdQuiz = 3,
                            CategoryName = "Podstawy IT"
                        });
                });

            modelBuilder.Entity("QuizApp.Data.Entities.Answer", b =>
                {
                    b.HasOne("QuizApp.Data.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("IdQuestion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizApp.Data.Entities.Question", b =>
                {
                    b.HasOne("QuizApp.Data.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("IdQuiz")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizApp.Data.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("QuizApp.Data.Entities.Quiz", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
